server {
    listen [::]:80 default_server;
    listen 80 default_server;
    server_name _;

    absolute_redirect off;

    root /;

    # Liveness probe
    location = /service/up {
        return 204;
    }

    # Health probe
    location = /service/health {
        return 204;
    }

    location ~* ^/api/(.*)$ {
        proxy_pass http://$SERVICE_API_HOST$request_uri;
    }

    location ~* ^/oauth/(.*)$ {
        proxy_pass http://$SERVICE_API_HOST$request_uri;
    }

    location ~* ^/session/(.*)$ {
        proxy_pass http://$SERVICE_API_HOST$request_uri;
    }

    location ~* ^/(.*)$ {
        proxy_pass http://$SERVICE_WEB_HOST$request_uri;
    }

    #expires -1;
    #add_header Pragma "no-cache";
    #add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
    #add_header X-Xss-Protection "1; mode=block" always;
    #add_header X-Frame-Options "SAMEORIGIN" always;

    #add_header Access-Control-Allow-Credentials "true" always;
    #add_header Access-Control-Allow-Methods "GET, POST, DELETE, PUT, PATCH, OPTIONS" always;
    #add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Content-Disposition,Content-Transfer-Encoding,Authorization,Device-Id" always;
    #add_header Access-Control-Expose-Headers "Content-Length,Content-Range" always;

    #proxy_set_header Host $host;
    #proxy_set_header X-Real-IP $remote_addr;
    #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
